//! FFI bindings for libifconfig
//!
//! This module provides minimal bindings to FreeBSD's libifconfig library
//! for network interface management. The raw bindings are generated by
//! bindgen and wrapped in safe Rust abstractions.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/freebsd.rs"));
